namespace petit.Models.ThingsBoard
{
  public enum AuditActionType
  {
    ADDED = 1,
    DELETED = 2,
    UPDATED = 3,
    ATTRIBUTESUPDATED = 4,
    ATTRIBUTESDELETED = 5,
    TIMESERIESUPDATED = 6,
    TIMESERIESDELETED = 7,
    RPCCALL = 8,
    CREDENTIALSUPDATED = 9,
    ASSIGNEDTOCUSTOMER = 10,
    UNASSIGNEDFROMCUSTOMER = 11,
    ACTIVATED = 12,
    SUSPENDED = 13,
    CREDENTIALSREAD = 14,
    ATTRIBUTESREAD = 15,
    RELATIONADDORUPDATE = 16,
    RELATIONDELETED = 17,
    RELATIONSDELETED = 18,
    ALARMACK = 19,
    ALARMCLEAR = 20,
    LOGIN = 21,
    LOGOUT = 22,
    LOCKOUT = 23,
    ASSIGNEDFROMTENANT = 24,
    ASSIGNEDTOTENANT = 25,
    PROVISIONSUCCESS = 26,
    PROVISIONFAILURE = 27
  }
}